# Generated by Django 4.2.5 on 2024-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
